spring:
    application:
        name: Comics_store
    datasource:
        username: eds
        password: eds
        url: jdbc:postgresql://localhost:5432/comics_store
    jpa:
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate:
                ddl-auto: none
