spring:
    application:
        name: Comics_store
    datasource:
        username: eds
        password: eds
        driver-class-name: com.postgresql.Driver
        url: jdbc:mysql://localhost:5432/comics_store
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgresSQLDialect
