insert into cart_data (id, size) values (1, 5);
insert into cart_data (id, size) values (2, 5);
insert into cart_data (id, size) values (3, 1);
insert into cart_data (id, size) values (4, 7);
insert into cart_data (id, size) values (5, 4);
insert into cart_data (id, size) values (6, 3);
insert into cart_data (id, size) values (7, 14);
insert into cart_data (id, size) values (8, 10);
insert into cart_data (id, size) values (9, 1);
insert into cart_data (id, size) values (10, 10);
insert into cart_data (id, size) values (11, 3);
insert into cart_data (id, size) values (12, 1);
insert into cart_data (id, size) values (13, 3);
insert into cart_data (id, size) values (14, 3);
insert into cart_data (id, size) values (15, 2);
insert into cart_data (id, size) values (16, 5);
insert into cart_data (id, size) values (17, 5);
insert into cart_data (id, size) values (18, 7);
insert into cart_data (id, size) values (19, 3);
insert into cart_data (id, size) values (20, 12);

select setval('cart_data_id_seq', (select max(id) from cart_data));
