insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (1, 'L''attacco dei Giganti', 7.19, 2019, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (2, 'Full Metal Alchemist', 1.73, 2011, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (3, 'Naruto', 6.86, 2004, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (4, 'I Tre Adolf', 2.23, 2008, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (5, 'Dragon Ball', 8.02, 2022, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (6, 'One Piece', 8.6, 1997, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (7, 'Slam Dunk', 8.74, 1994, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (8, 'My Hero Academia', 2.66, 1997, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (9, 'Le Bizzarre Avventure di Jojo', 5.02, 2002, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (10, 'Hunter X Hunter', 1.32, 1997, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (11, 'Tex', 7.05, 1992, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (12, 'Diabolik', 3.92, 1999, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (13, 'Dylan Dog', 1.56, 1997, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (14, 'Ogni Maledetto Lunedì su Due', 4.79, 2018, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (15, 'Ratman', 8.66, 2018, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (16, 'Guanto dell''Infinito', 6.65, 2000, null, true, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (17, 'X-Men: The Dark Phoenix Saga', 8.92, 2002, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (18, 'Amazing Spider-Man: The Night Gwen Stacy Died', 2.94, 2017, null, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (19, 'Guerra Civile', 7.56, null, 2016, false, 'description', 1);
insert into collection (id, name, price, year_of_release, format_and_binding, color, description, version) values (20, 'Daredevil: Born Again', 3.62, 2004, null, true, 'description', 1);
