insert into author (id, name, biography, version) values (1, 'Hajime Isayama', 'biography', 1);
insert into author (id, name, biography, version) values (2, 'Hiromu Arakawa', 'biography', 1);
insert into author (id, name, biography, version) values (3, 'Masashi Kishimoto', 'biography', 1);
insert into author (id, name, biography, version) values (4, 'Osamu Tezuka', 'biography', 1);
insert into author (id, name, biography, version) values (5, 'Akira Toriyama', 'biography', 1);
insert into author (id, name, biography, version) values (6, 'Eiichirō Oda', 'biography', 1);
insert into author (id, name, biography, version) values (7, 'Takehiko Inoue', 'biography', 1);
insert into author (id, name, biography, version) values (8, 'Kōhei Horikoshi', 'biography', 1);
insert into author (id, name, biography, version) values (9, 'Hirohiko Araki', 'biography', 1);
insert into author (id, name, biography, version) values (10, 'Yoshihiro Togashi', 'biography', 1);
insert into author (id, name, biography, version) values (11, 'Ruju Pasquale', 'biography', 1);
insert into author (id, name, biography, version) values (12, 'Ortiz José', 'biography', 1);
insert into author (id, name, biography, version) values (13, 'Villa Claudio', 'biography', 1);
insert into author (id, name, biography, version) values (14, 'Boselli Mauro', 'biography', 1);
insert into author (id, name, biography, version) values (15, 'Andreucci Stefano', 'biography', 1);
insert into author (id, name, biography, version) values (16, 'Faraci Tito', 'biography', 1);
insert into author (id, name, biography, version) values (17, 'Mastantuono Corrado', 'biography', 1);
insert into author (id, name, biography, version) values (18, 'Nizzi Claudio', 'biography', 1);
insert into author (id, name, biography, version) values (19, 'Filippuci Lucio', 'biography', 1);
insert into author (id, name, biography, version) values (20, 'Acciarino Gianluca', 'biography', 1);
insert into author (id, name, biography, version) values (21, 'Frisenda Pasquale', 'biography', 1);
insert into author (id, name, biography, version) values (22, 'Zerocalcare', 'biography', 1);
insert into author (id, name, biography, version) values (23, 'Gerry Conway', 'biography', 1);
insert into author (id, name, biography, version) values (24, 'Gil Kane', 'biography', 1);

select setval('author_id_seq', (select max(id) from author));
