insert into classification (category_id, collection_id) values ('Avventura', 'One Piece');
insert into classification (category_id, collection_id) values ('Umoristico', 'One Piece');
insert into classification (category_id, collection_id) values ('Avventura', 'Dragon Ball');
insert into classification (category_id, collection_id) values ('Horror', 'I Tre Adolf');
insert into classification (category_id, collection_id) values ('Manga', 'Black Jack');
insert into classification (category_id, collection_id) values ('Manga', 'Detective Conan');
insert into classification (category_id, collection_id) values ('Manga', 'Naruto');
insert into classification (category_id, collection_id) values ('Manga', 'Slam Dunk');
insert into classification (category_id, collection_id) values ('Manga', 'Demon Slayer');
insert into classification (category_id, collection_id) values ('Horror', 'L Attacco Dei Giganti');
insert into classification (category_id, collection_id) values ('Manga', 'Fairy Tail');
insert into classification (category_id, collection_id) values ('Manga', 'My Hero Academia');
insert into classification (category_id, collection_id) values ('Horror', 'Tokyo Ghoul');
insert into classification (category_id, collection_id) values ('Avventura', 'Tex');
insert into classification (category_id, collection_id) values ('Avventura', 'Diabolik');
insert into classification (category_id, collection_id) values ('Avventura', 'Dylan Dog');
