insert into collection (name, price, year_of_release, color, description) values ('One Piece', 18.32, 1985, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Dragon Ball', 21.77, 2006, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('I Tre Adolf', 16.97, 1983, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Black Jack', 7.65, 1984, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Detective Conan', 3.27, 1993, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Naruto', 12.22, 2001, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Slam Dunk', 21.45, 2018, false, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Demon Slayer', 3.66, 2010, false, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('L Attacco Dei Giganti', 25.11, 2021, false, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Fairy Tail', 18.96, 1996, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('My Hero Academia', 24.72, 2011, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Tokyo Ghoul', 5.32, 1991, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Tex', 8.46, 2008, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Diabolik', 15.96, 1981, true, 'Description');
insert into collection (name, price, year_of_release, color, description) values ('Dylan Dog', 15.21, 2021, false, 'Description');
